(()=>{
const PRINTER_NAME='KPOS Zy307',PRINTER_IP='192.168.1.199',PRINTER_PORT=9100;
let autoTimer=null,lastOrders=[];
const getAuto=()=>localStorage.getItem('r971_auto_print')==='1';
const setAuto=v=>localStorage.setItem('r971_auto_print',v?'1':'0');
function printedSet(){try{return new Set(JSON.parse(localStorage.getItem('r971_printed_orders')||'[]'))}catch{return new Set()}}
function rememberPrinted(id){const s=printedSet();s.add(id);localStorage.setItem('r971_printed_orders',JSON.stringify([...s].slice(-150)))}
async function printerStatus(){try{const d=await api('POST',{action:'printer_status',pin});const el=document.getElementById('printerState');if(!el)return;el.innerHTML=d.online?'<span style="color:#15803d;font-weight:900">● PRINT BRIDGE ĐANG ONLINE</span>':'<span style="color:#b91c1c;font-weight:900">● PRINT BRIDGE CHƯA KẾT NỐI</span>';if(d.bridge?.last_seen)el.innerHTML+=`<div class="muted">Cập nhật: ${new Date(d.bridge.last_seen).toLocaleString('vi-VN')}</div>`}catch{}}
async function testPrint(){try{const d=await api('POST',{action:'print_test',pin});toast('Đã gửi lệnh IN THỬ');setTimeout(printerStatus,1500)}catch(e){toast(e.message)}}
async function fetchToday(){const date=document.getElementById('selectedDate')?.value||localToday();const d=await api('POST',{action:'staff',pin,selected_date:date});lastOrders=d.orders||[];return d}
async function printOrderId(id,code){try{await api('POST',{action:'print_order',pin,order_id:id});toast('🖨️ Đã gửi bill '+code+' tới máy in');rememberPrinted(id)}catch(e){toast(e.message)}}
async function printByCode(code){try{const d=await fetchToday();const o=(d.orders||[]).find(x=>x.order_code===code);if(!o)return toast('Không tìm thấy đơn '+code);await printOrderId(o.id,o.order_code)}catch(e){toast(e.message)}}
window.r971PrintByCode=printByCode;
async function autoCheck(){if(!getAuto()||!pin)return;const date=document.getElementById('selectedDate')?.value||localToday();if(date!==localToday())return;try{const d=await fetchToday(),done=printedSet();for(const o of [...(d.orders||[])].reverse()){if(o.status==='cancelled'||done.has(o.id))continue;await printOrderId(o.id,o.order_code)}}catch{}}
function enhanceOrders(){document.querySelectorAll('#orders .order').forEach(card=>{if(card.dataset.printEnhanced)return;card.dataset.printEnhanced='1';const m=card.textContent.match(/Mã đơn:\s*([^\s]+)/i);if(!m)return;const code=m[1];if(card.textContent.includes('ĐÃ HỦY'))return;const b=document.createElement('button');b.className='primary';b.style.cssText='margin-top:10px;width:100%;background:#0f766e';b.textContent='🖨️ IN BILL';b.onclick=()=>printByCode(code);card.appendChild(b)})}
function insertUI(){const panel=document.getElementById('panel');if(!panel||document.getElementById('printerCard'))return;const card=document.createElement('div');card.id='printerCard';card.className='card';card.innerHTML=`<div class="top"><div><b style="font-size:18px">🖨️ MÁY IN BILL</b><div class="muted">${PRINTER_NAME} · ${PRINTER_IP}:${PRINTER_PORT}</div></div><button class="ghost" onclick="window.r971PrinterStatus()">LÀM MỚI</button></div><div id="printerState" style="margin:10px 0">Đang kiểm tra Print Bridge...</div><div class="row"><button class="primary" onclick="window.r971TestPrint()">🧾 IN THỬ</button><label class="card" style="margin:0;display:flex;align-items:center;gap:10px;cursor:pointer"><input id="autoPrintToggle" type="checkbox" style="width:auto" ${getAuto()?'checked':''}><span><b>TỰ ĐỘNG IN ĐƠN MỚI</b><div class="muted">Máy Windows ở quầy phải mở Print Bridge.</div></span></label></div>`;panel.insertBefore(card,panel.children[1]||null);document.getElementById('autoPrintToggle').addEventListener('change',e=>{setAuto(e.target.checked);toast(e.target.checked?'Đã bật tự động in':'Đã tắt tự động in');if(e.target.checked)autoCheck()});printerStatus();}
window.r971PrinterStatus=printerStatus;window.r971TestPrint=testPrint;
const obs=new MutationObserver(()=>{insertUI();enhanceOrders()});window.addEventListener('load',()=>{insertUI();enhanceOrders();printerStatus();autoTimer=setInterval(()=>{printerStatus();autoCheck();enhanceOrders()},5000)});obs.observe(document.documentElement,{childList:true,subtree:true});
})();
